package com.dangabito.projects.MovieManagement.util;

public enum MovieGenre {
	ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HORROR, MUSIC, MYSTERY, ROMANCE,
	SCIENCE_FICTION, THRILLER

}
